### ISSUE TITLE
Visual Studio 2015 does not find many packages

### ISSUE THREAD

**Issue by ElenaLenchic** [bower/bower.github.io#264]
Hi all,
I have faced an issue that Bower Package Manager for Visual Studio 2015 does not display many of the packages. I.e. (strange exapmle) it displays 'font-awesome', but do not 'fontawesome'. Yet they both reference the same repository.
Another example jquery-easing package is not displayed in Visual Studio. There are a lot of other packages that cannot be found (and installed) through Visual Studio UI.
I have posted a question in social.msdn (https://social.msdn.microsoft.com/Forums/vstudio/en-US/bcf8f403-ac9a-4d3c-8471-a9e2e2ff119e/bower-package-manager-in-visual-studio-2015-does-not-find-bower-packages?forum=visualstudiogeneral). The reply was that is somehow related to compatibility with IE. 
I tried to search packages in Edge, but I have got and exception in console: 
SCRIPT5009: 'Promise' is undefined
What could be the reason? How to make it work?

**Comment by julmot** [comment]
I'm not using Visual Studio, but maybe someone else @bower/bower-website?

**Comment by fernandoguedes** [comment]
I'm not.

**Comment by ElenaLenchic** [comment]
I have troubles event searching in IE11. Does https://bower.io/search/ supports IE11?

**Comment by BenMann** [comment]
@ElenaLenchic It should.. Can you please be more specific about what you mean by "troubles"?
- Is there an error on the console?
- Are there no results returned?
- Is a request to the server made at all?
- Are you referring to something visually wrong?

**Comment by ElenaLenchic** [comment]
> I tried to search packages in **IE11**, but I have got and exception in console: 
> SCRIPT5009: 'Promise' is undefined
> What could be the reason? How to make it work?

**Comment by riyadhalnur** [comment]
I think we need to use a Promise polyfill.

**Comment by julmot** [comment]
@sheerun Seems like you've introduced this issue. You've used [fetch](https://github.com/github/fetch) without polyfill.

**Comment by sheerun** [comment]
I use whatwg-fetch polyfill, see Gruntfile.js

**Comment by ElenaLenchic** [comment]
As for IE 11 it is a known issue, this probably causes the problems in Visual Studio. Is there any workaround?

**Comment by sheerun** [comment]
I think the Promise polyfill is missing, I'll fix it asap

**Comment by sheerun** [comment]
Should work now

**Comment by ElenaLenchic** [comment]
Yes, it works in IE11 and Edge. But for Visual Studio the problem remains the same.
